spring:
  banner:
    charset: utf-8
  http:
   encoding:
     charset: UTF-8
     enabled: true
     force: true
  messages:
    encoding: UTF-8
  datasource:
       url: jdbc:mysql://127.0.0.1:3306/lin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
       username: root
       password: 123
       driver-class-name: com.mysql.cj.jdbc.Driver

# 打印SQL日志 ,键值对的形式 来配置
logging:
  level:
    org.learn.boot.cache.mapper: debug
server:
  port: 8090

dubbo:
  application:
    name: provider-ticket
  scan:
  # 配置写好了之后怎么将服务发布出去呢？ 这时需要在service上添加 暴露服务的@Service注解
    base-packages: org.learn.boot.dubbo.ticket.service
  registry:
    address: 192.168.199.115:2181,192.168.199.116:2181,192.168.199.117:2181
    protocol: zookeeper



