
spring:
  banner:
    charset: utf-8
  http:
   encoding:
     charset: UTF-8
     enabled: true
     force: true
  messages:
    encoding: UTF-8
  datasource:
       url: jdbc:mysql://127.0.0.1:3306/lin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
       username: root
       password: 123
       driver-class-name: com.mysql.cj.jdbc.Driver

#  elasticsearch:
  # 使用jest 来连接 es
  #启动成功后会打印  main] io.searchbox.client.AbstractJestClient   : Setting server pool to a list of 1 servers: [http://192.168.199.201:9200/]
#       jest:
#         uris: http://192.168.199.201:9200/

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.199.202:9300

# 打印SQL日志 ,键值对的形式 来配置
logging:
  level:
    org.learn.boot.cache.mapper: debug
server:
  port: 8090